# fly.toml app configuration file generated for invitation on 2023-09-27T11:51:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "invitation"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
